name: Deploy Protected Site

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Encrypt index.html
      uses: robinmoisson/staticrypt@v2.0.0
      with:
        path: index.html
        password: ${{ secrets.PASSWORD }}
        destination: index.html
        config: |
          {
            "color": "#000000",
            "backgroundColor": "#ffffff",
            "image": {
              "src": "https://staticrypt.net/img/logo.png",
              "width": 300,
              "height": 300
            },
            "title": "Acceso restringido"
          }

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
